[project]
name = "pyframe"
version = "0.1.0"
description = "A fullscreen photo-frame / slideshow application built with Pygame"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
    "pgzero>=1.2.1",
    "pydantic-settings>=2.11.0"
]
